config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  resources :topics
  devise_for :users

  root to: "home#index"

  resources :categories
  resources :messages
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :delete_all
  belongs_to :category
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description, :category_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.slim
= form_for @topic do |f|
  - if @topic.errors.any?
    #error_explanation
      h2 = "#{pluralize(@topic.errors.count, "error")} prohibited this topic from being saved:"
      ul
        - @topic.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :category
    = f.text_field :category
  .actions = f.submit

app/views/topics/edit.html.slim
h1 Editing topic

== render 'form'

=> link_to 'Show', @topic
'|
=< link_to 'Back', topics_path

app/views/topics/index.html.slim
h1 Listing topics

table
  thead
    tr
      th Title
      th Description
      th Category
      th
      th
      th

  tbody
    - @topics.each do |topic|
      tr
        td = topic.title
        td = topic.description
        td = topic.category
        td = link_to 'Show', topic
        td = link_to 'Edit', edit_topic_path(topic)
        td = link_to 'Destroy', topic, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Topic', new_topic_path

app/views/topics/new.html.slim
h1 New topic

== render 'form'

= link_to 'Back', topics_path

app/views/topics/show.html.slim
p#notice = notice

p
  strong Title:
  = @topic.title
p
  strong Description:
  = @topic.description
p
  strong Category:
  = @topic.category

=> link_to 'Edit', edit_topic_path(@topic)
'|
=< link_to 'Back', topics_path